### PR TITLE
 biryani recipe.txt

### PR DESCRIPTION
**Pull request by Venkatreddy-1706**
biryani added

### CODE REVIEW

**Comment by Venkatreddy-1706** [comment]
Thanks!

**Comment by Venkatreddy-1706** [comment]
Thanks!

**Comment by Venkatreddy-1706** [comment]
@Venkatreddy17  thanks!

**Comment by Venkatreddy17** [comment]
@Venkatreddy-1706  Wellcome

**Comment by Venkatreddy17** [comment]
done!

**Pull request merged**
